### ISSUE TITLE
`"changePlayerListName": true` causes `%styled-nicknames:display_name%` to crash, even when set back to `false`

### ISSUE THREAD

**Issue by Zeklandia** [Patbox/StyledNicknames#1]
After setting `"changePlayerListName"` to `true` in `styled-nicknames.json` and reloading config, attempts by other plugins to resolve `%styled-nicknames:display_name%` (in this case [StyledPlayerList](https://github.com/Patbox/StyledPlayerList)) would crash the server:

```
java.lang.ClassCastException: class net.minecraft.class_3244 cannot be cast to class net.minecraft.class_3222 (net.minecraft.class_3244 and net.minecraft.class_3222 are in unnamed module of loader net.fabricmc.loader.launch.knot.KnotClassLoader @1040be71)
    at net.minecraft.class_3244.sn_getOutputOrVanilla(class_3244.java:2731)
    at eu.pb4.stylednicknames.StyledNicknamesMod.lambda$onInitialize$1(StyledNicknamesMod.java:28)
    at eu.pb4.placeholders.util.PlaceholderUtils.parsePlaceholderFromMap(PlaceholderUtils.java:227)
    at eu.pb4.placeholders.util.PlaceholderUtils.recursivePlaceholderParsing(PlaceholderUtils.java:60)
    at eu.pb4.placeholders.util.PlaceholderUtils.recursivePlaceholderParsing(PlaceholderUtils.java:80)
    at eu.pb4.placeholders.PlaceholderAPI.parseText(PlaceholderAPI.java:46)
    at eu.pb4.styledplayerlist.config.Config.formatPlayerUsername(Config.java:57)
    at net.minecraft.class_3222.handler$bgc000$changePlayerListName(class_3222.java:8764)
    at net.minecraft.class_3222.method_14206(class_3222.java)
    at net.minecraft.class_2703.<init>(class_2703.java:28)
    at net.minecraft.class_3324.method_14611(class_3324.java:394)
    at net.minecraft.class_3244.method_10839(class_3244.java:1135)
    at net.minecraft.class_2535.method_10768(class_2535.java:413)
    at net.minecraft.class_3242.method_14357(class_3242.java:196)
    at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:902)
    at net.minecraft.class_3176.method_3813(class_3176.java:335)
    at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:831)
    at net.minecraft.server.MinecraftServer.handler$zpg000$modifiedRunLoop(MinecraftServer.java:5890)
    at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676)
    at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
    at java.base/java.lang.Thread.run(Thread.java:831)
```

Setting it back to `false` and reloading config again did not stop the crashes. Deleting player data from `world/data` and `world/player-data-api` did not fix the issue. As long as `%styled-nicknames:display_name%` was used by StyledPlayerList, every player received an "Invalid player data" error when attempting to connect to the server. Once every reference to `%styled-nicknames:display_name%` was removed, the problem was gone.

**Comment by Patbox** [comment]
Fixed on latest

**Comment by Zeklandia** [comment]
This might need to be reopened. After the update, `/boxofplaceholders string %styled-nicknames:display_name%` worked and no longer crashed the server. Add `%styled-nicknames:display_name%` to the StyledPlayerList configuration also worked, in that player nicknames started showing up in the player list.

However, after adding it to the StyledPlayerList configuration, any new attempts to connect to the server failed with the same "Invalid player data" message, which went away once `%styled-nicknames:display_name%` was removed from the StyledPlayerList configuration and reloaded. No one who stayed connected was kicked, and the server did not crash, both of which are improvements from before the recent update.

Here's what shows up in the server logs when players try to connect after adding `%styled-nicknames:display_name%` to the StyledPlayerList configuration.
```
[21:38:57] [User Authenticator #18/INFO]: UUID of player [player] is [UUID]
[21:38:58] [Server thread/INFO]: [player][/[IP:port]] logged in with entity id 112263 at (3381.0791438681586, 14.0, 15.7008379911084)
[21:38:58] [Server thread/INFO]: com.mojang.authlib.GameProfile@4e1c0344[id=[UUID],name=[player],properties={textures=[com.mojang.authlib.properties.Property@3c26c85d]},legacy=false] (/[IP:port]) lost connection: Invalid player data
[21:38:58] [Server thread/WARN]: handleDisconnection() called twice
```

**Comment by Patbox** [comment]
Huh, could you add this mod and test it again? https://github.com/Tom-The-Geek/WDMNF/releases/download/v1.0.0%2Bmc.1.17/wdmnf-1.0.0+mc.1.17.jar It should show more logs

**Comment by Zeklandia** [comment]
I have narrowed it down: the error happens when `"changePlayerName"` is set to `true` (`false` by default) in `config/styledplayerlist/config.json`. The error happens regardless of the values of `"changeDisplayName"` and `"changePlayerListName"` in `config/styled-nicknames.json`.

If I leave `"changePlayerName"` set to `false` in `config/styledplayerlist/config.json`, and instead set `"changePlayerListName"` to `true` in `config/styled-nicknames.json`, the nickname will show in the player list and there is no connection issue, all that's missing is the rank formatting from StyledPlayerList.

**Comment by Patbox** [comment]
Interesting. I will look into that

**Comment by Zeklandia** [comment]
I tested StyledPlayerList 2.1.1 and it does not crash under these circumstances. It worked fine whether StyledNicknames or StyledPlayerList or both were set to change the player list name.

**Comment by Patbox** [comment]
It's not really fixed, I just "hardened" StyledPlayerList to not kick out players when it happens. It's still a bug that needs to be fixed (on next release some day)
